"""Thin integration boundary around pyKT 0.0.38.

This module deliberately does not vendor pyKT or its data. pyKT owns model
classes and standard training; this project owns canonical records, probes,
and target-level analysis.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .env import configure_environment

configure_environment()


def preprocess_dataset(
    dataset_name: str,
    raw_path: str | Path,
    output_dir: str | Path,
    *,
    metadata_dir: str | Path | None = None,
    task_name: str = "task_3_4",
    min_seq_len: int = 3,
    maxlen: int = 200,
    kfold: int = 5,
    cpu_threads: int = 20,
) -> Path:
    """Run pyKT preprocessing and return the generated ``data.txt`` path.

    The NIPS adapter calls pyKT's low-level function because pyKT 0.0.38
    assumes metadata is a child of the raw file directory, while the official
    Eedi layout stores ``metadata`` beside ``train_data``.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    raw_path = Path(raw_path)
    if not raw_path.exists():
        raise FileNotFoundError(f"Raw dataset not found: {raw_path}")
    data_txt = output_dir / "data.txt"

    if dataset_name == "nips_task34":
        if metadata_dir is None:
            raise ValueError("metadata_dir is required for nips_task34")
        if not Path(metadata_dir).exists():
            raise FileNotFoundError(f"Metadata directory not found: {metadata_dir}")
        from pykt.preprocess.nips_task34_preprocess import read_data_from_csv

        read_data_from_csv(str(raw_path), str(metadata_dir), task_name, str(data_txt))
    elif dataset_name == "assist2009":
        from pykt.preprocess.assist2009_preprocess import read_data_from_csv

        read_data_from_csv(str(raw_path), str(data_txt))
    else:
        raise ValueError(f"Unsupported pilot dataset: {dataset_name}")

    config_path = output_dir / "pykt_data_config.json"
    split_concept_and_question(
        dataset_name,
        data_txt,
        output_dir,
        config_path,
        min_seq_len=min_seq_len,
        maxlen=maxlen,
        kfold=kfold,
    )
    return data_txt


def _configure_preprocess_threads(cpu_threads: int) -> None:
    """Set BLAS/OpenMP pools used by pandas/NumPy before preprocessing starts."""
    import os

    if cpu_threads < 1:
        raise ValueError("cpu_threads must be positive")
    for variable in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS", "NUMEXPR_NUM_THREADS"):
        os.environ[variable] = str(cpu_threads)


def split_concept_and_question(
    dataset_name: str,
    data_txt: str | Path,
    output_dir: str | Path,
    config_path: str | Path,
    *,
    min_seq_len: int = 3,
    maxlen: int = 200,
    kfold: int = 5,
) -> None:
    """Generate pyKT concept-level and question-level split artifacts."""
    from pykt.preprocess.split_datasets import main as split_concept
    from pykt.preprocess.split_datasets_que import main as split_question

    output_dir = Path(output_dir)
    config_path = Path(config_path)
    config_path.write_text(json.dumps({dataset_name: {}}, indent=2))
    # pyKT's question splitter expects the concept-level config entry to exist
    # and augments it with the question-level filenames.
    split_concept(
        str(output_dir), str(data_txt), dataset_name, str(config_path),
        min_seq_len=min_seq_len, maxlen=maxlen, kfold=kfold,
    )
    split_question(
        str(output_dir), str(data_txt), dataset_name, str(config_path),
        min_seq_len=min_seq_len, maxlen=maxlen, kfold=kfold,
    )


def load_generated_config(path: str | Path, dataset_name: str) -> dict[str, Any]:
    """Load the pyKT config generated by the splitters."""
    payload = json.loads(Path(path).read_text())
    return payload[dataset_name]
